### ISSUE TITLE
What about imgs with sizes @3х @4х?

### ISSUE THREAD

**Issue by jt3k** [reducejs/gulp.spritesmith-multi#4]
subj &uarr;

[](https://github.com/CSSSR/csssr-project-template/issues/109)

**Comment by zoubin** [comment]
@jt3k 
It seems that [gulp.spritesmith](https://github.com/twolfson/gulp.spritesmith/blob/master/lib/gulp-spritesmith.js#L209) can only handle 2x.
Maybe you could submit an issue there.

I'm closing this now.
